### ISSUE TITLE
Map.jinja points to the incorrect (old) repositories.

### ISSUE THREAD

**Issue by lmdv** [saltstack-formulas/owncloud-formula#8]
The new repositories are at https://download.owncloud.org/download/repositories/stable

**Comment by babilen** [comment]
How would you adapt those for the different releases supported in map.jinja ?

**Comment by lmdv** [comment]
I would incorporate Wenzel's branch to generalize the formula a bit. (https://github.com/Wenzel/owncloud-formula). And use the following path as base: http://download.owncloud.org/download/repositories/stable/
